version: 2
updates:
  # GitHub Actions - Master branch
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: master
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # GitHub Actions - v3.5 branch
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: v3.5
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Docker - Master branch
  - package-ecosystem: docker
    directories:
      - "/docker/frontend"
      - "/docker/standard"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: master
    groups:
      docker-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      docker-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Docker - v3.5 branch
  - package-ecosystem: docker
    directories:
      - "/docker/frontend"
      - "/docker/standard"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: v3.5
    groups:
      docker-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      docker-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # NPM - Master branch
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: master
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # NPM - v3.5 branch
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: v3.5
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Python pip - Master branch
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: master
    groups:
      python-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Python pip - v3.5 branch
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: v3.5
    groups:
      python-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-major:
        patterns:
          - "*"
        update-types:
          - "major"
