repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
#- repo: https://github.com/astral-sh/ruff-pre-commit
  #rev: v0.6.8
  #hooks:
    # Run the linter.
  #  - id: ruff
  #    types_or: [ python, pyi ]
  #    args: [ --fix ]
  #  # Run the formatter.
  #  - id: ruff-format
  #    types_or: [ python, pyi ]
