"project_id_env": CROWDIN_PROJ_ID
"api_token_env": CROWDIN_API_TOKEN
"base_path": "./ui2"
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

#
# Files configuration.
# See https://support.crowdin.com/developer/configuration-file/ for all available options
#
files: [
    {
      "source": "public/localization/en/_default.json",
      #
      # Translation files filter
      # e.g. "/resources/%two_letters_code%/%original_file_name%"
      #
      "translation": "public/localization/%two_letters_code%/_default.json"
    }
  ]
