# Docker compose file used for local development
#
# $ cat .env
#
#   PAPERMERGE__SECURITY__SECRET_KEY=123
#   PAPERMERGE__DATABASE__URL=sqlite:////db/db.sqlite3
#
version: "3.9"
x-backend: &common  # yaml anchor definition
  build:
    context: .
    dockerfile: docker/dev/Dockerfile
    args:
      VERSION: 3.0dev14
  volumes:
      - ./papermerge:/core_app/papermerge/
      - ./ui:/core_ui/
      - ./docker/dev/db:/db
      - ./media_root:/core_app/media
  environment:
    PAPERMERGE__SECURITY__SECRET_KEY: ${PAPERMERGE__SECURITY__SECRET_KEY}
    PAPERMERGE__DATABASE__URL: ${PAPERMERGE__DATABASE__URL}
    PAPERMERGE__REDIS__URL: ${PAPERMERGE__REDIS__URL}
    PAPERMERGE__AUTH__GOOGLE_CLIENT_SECRET: ${PAPERMERGE__AUTH__GOOGLE_CLIENT_SECRET}
    PAPERMERGE__AUTH__GOOGLE_CLIENT_ID: ${PAPERMERGE__AUTH__GOOGLE_CLIENT_ID}
    PAPERMERGE__AUTH__GOOGLE_AUTHORIZE_URL: ${PAPERMERGE__AUTH__GOOGLE_AUTHORIZE_URL}
    PAPERMERGE__AUTH__GOOGLE_REDIRECT_URI: ${PAPERMERGE__AUTH__GOOGLE_REDIRECT_URI}
    PAPERMERGE__AUTH__GITHUB_CLIENT_SECRET: ${PAPERMERGE__AUTH__GITHUB_CLIENT_SECRET}
    PAPERMERGE__AUTH__GITHUB_CLIENT_ID: ${PAPERMERGE__AUTH__GITHUB_CLIENT_ID}
    PAPERMERGE__AUTH__GITHUB_AUTHORIZE_URL: ${PAPERMERGE__AUTH__GITHUB_AUTHORIZE_URL}
    PAPERMERGE__AUTH__GITHUB_REDIRECT_URI: ${PAPERMERGE__AUTH__GITHUB_REDIRECT_URI}
    PAPERMERGE__SEARCH__URL: ${PAPERMERGE__SEARCH__URL}
services:
  backend:
    <<: *common
    ports:
     - "11000:80"
    depends_on:
      - solr
      - redis
  worker:
    <<: *common
    command: worker
  redis:
    image: redis:6
  solr:
    image: solr:9.3
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - pmg_index2

volumes:
  data:
