# Generated by Django 4.2.13 on 2024-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_customfield_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="path_template",
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
