# Generated by Django 4.2.13 on 2024-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_customfield_id_alter_customfieldinstance_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomFieldInstance",
            new_name="CustomFieldValue",
        ),
        migrations.AlterModelOptions(
            name="customfieldvalue",
            options={"ordering": ("created",)},
        ),
        migrations.RemoveConstraint(
            model_name="customfieldvalue",
            name="core_customfieldinstance_unique_document_field",
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.UniqueConstraint(
                fields=("document", "field"),
                name="core_customfieldvalue_unique_document_field",
            ),
        ),
    ]
