# Generated by Django 4.2.13 on 2024-09-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_customfieldinstance_customfieldvalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="user",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_fields",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
