# Generated by Django 4.2.13 on 2024-10-01 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_customfield_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customfield",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="customfieldvalue",
            options={"ordering": ("created_at",)},
        ),
        migrations.RemoveField(
            model_name="customfield",
            name="created",
        ),
        migrations.RemoveField(
            model_name="customfieldvalue",
            name="created",
        ),
        migrations.AddField(
            model_name="customfield",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created_at",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created_at",
            ),
        ),
    ]
