# Generated by Django 4.0.8 on 2023-01-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_basetreenode_options_remove_basetreenode_level_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='basetreenode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('parent', 'title'), name='parent_title_uniq_when_parent_is_null'),
        ),
    ]
