# Generated by Django 4.0.8 on 2023-01-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_basetreenode_parent_title_uniq_when_parent_is_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='basetreenode',
            name='parent_title_uniq_when_parent_is_null',
        ),
        migrations.AddConstraint(
            model_name='basetreenode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('title',), name='title_uniq_when_parent_is_null'),
        ),
    ]
