# Generated by Django 4.2.13 on 2024-10-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_documenttypecustomfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfieldvalue",
            name="value_monetary",
            field=models.DecimalField(decimal_places=2, max_digits=36, null=True),
        ),
    ]
