# Generated by Django 3.0.10 on 2020-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201002_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='digest',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
