# Generated by Django 3.2.7 on 2021-10-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20211026_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_folder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_owner', to='core.folder'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inbox_folder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_owner', to='core.folder'),
        ),
    ]
