# Generated by Django 3.2.7 on 2021-11-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20211110_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
    ]
