# Generated by Django 3.2.7 on 2021-11-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20211110_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
