# Generated by Django 3.2.7 on 2021-11-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_documentversion_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='lang',
            field=models.CharField(default='deu', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='size',
            field=models.BigIntegerField(default=0, help_text='Size of file_orig attached. Size is in Bytes'),
        ),
    ]
