# Generated by Django 3.2.9 on 2021-11-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_page_document_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='short_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
