# Generated by Django 3.2.9 on 2021-11-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_documentversion_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
