"""v3.6.0: 0003 --- Add SQL audit_log table

Revision ID: 6c5a56286b19
Revises: 5552ae28406c
Create Date: 2025-08-20 06:37:51.698694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c5a56286b19'
down_revision: Union[str, None] = '5552ae28406c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('table_name', sa.String(length=63), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('application', sa.String(length=50), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_operation', 'audit_log', ['operation'], unique=False)
    op.create_index('idx_audit_log_table_record', 'audit_log', ['table_name', 'record_id'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_log_user_id', table_name='audit_log')
    op.drop_index('idx_audit_log_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_log_table_record', table_name='audit_log')
    op.drop_index('idx_audit_log_operation', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
