"""add ondelete cascade to nodes tags

Revision ID: 88b6b2d497ea
Revises: f0e0da122a9a
Create Date: 2025-02-01 08:20:24.361716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88b6b2d497ea"
down_revision: Union[str, None] = "f0e0da122a9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "nodes_user_id_fkey",
        "nodes",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.drop_constraint("nodes_tags_node_id_fkey", "nodes_tags", type_="foreignkey")
    op.create_foreign_key(
        None, "nodes_tags", "nodes", ["node_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "tag_user_id_fk", "tags", "users", ["user_id"], ["id"], use_alter=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tag_user_id_fk", "tags", type_="foreignkey")
    op.drop_constraint(None, "nodes_tags", type_="foreignkey")
    op.create_foreign_key(
        "nodes_tags_node_id_fkey", "nodes_tags", "nodes", ["node_id"], ["id"]
    )
    op.drop_constraint("nodes_user_id_fkey", "nodes", type_="foreignkey")
    # ### end Alembic commands ###
