"""Set deferrable contraints

Revision ID: 89be7e6a3444
Revises: a07f7fbbcca8
Create Date: 2025-12-25 08:09:07.345444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '89be7e6a3444'
down_revision: Union[str, None] = 'a07f7fbbcca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_fields', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('custom_fields', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('custom_fields_updated_by_fkey'), 'custom_fields', type_='foreignkey')
    op.drop_constraint(op.f('custom_fields_created_by_fkey'), 'custom_fields', type_='foreignkey')
    op.create_foreign_key(None, 'custom_fields', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'custom_fields', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('document_types', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('document_types', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('document_types_created_by_fkey'), 'document_types', type_='foreignkey')
    op.drop_constraint(op.f('document_types_updated_by_fkey'), 'document_types', type_='foreignkey')
    op.create_foreign_key(None, 'document_types', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'document_types', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('document_versions', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('document_versions', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('document_versions_updated_by_fkey'), 'document_versions', type_='foreignkey')
    op.drop_constraint(op.f('document_versions_created_by_fkey'), 'document_versions', type_='foreignkey')
    op.create_foreign_key(None, 'document_versions', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'document_versions', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('groups', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('groups', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('groups_updated_by_fkey'), 'groups', type_='foreignkey')
    op.drop_constraint(op.f('groups_created_by_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'groups', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('nodes', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('nodes', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('nodes_updated_by_fkey'), 'nodes', type_='foreignkey')
    op.drop_constraint(op.f('nodes_created_by_fkey'), 'nodes', type_='foreignkey')
    op.create_foreign_key(None, 'nodes', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'nodes', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('roles', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('roles', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('roles_updated_by_fkey'), 'roles', type_='foreignkey')
    op.drop_constraint(op.f('roles_created_by_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('shared_nodes', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('shared_nodes', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('shared_nodes_updated_by_fkey'), 'shared_nodes', type_='foreignkey')
    op.drop_constraint(op.f('shared_nodes_created_by_fkey'), 'shared_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'shared_nodes', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'shared_nodes', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('tags', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tags', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('tags_created_by_fkey'), 'tags', type_='foreignkey')
    op.drop_constraint(op.f('tags_updated_by_fkey'), 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'tags', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.drop_constraint(op.f('users_updated_by_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_created_by_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('users_groups', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users_groups', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('users_groups_created_by_fkey'), 'users_groups', type_='foreignkey')
    op.drop_constraint(op.f('users_groups_updated_by_fkey'), 'users_groups', type_='foreignkey')
    op.create_foreign_key(None, 'users_groups', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'users_groups', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.alter_column('users_roles', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users_roles', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('users_roles_updated_by_fkey'), 'users_roles', type_='foreignkey')
    op.drop_constraint(op.f('users_roles_created_by_fkey'), 'users_roles', type_='foreignkey')
    op.create_foreign_key(None, 'users_roles', 'users', ['updated_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'users_roles', 'users', ['created_by'], ['id'], ondelete='RESTRICT', initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_roles', type_='foreignkey')
    op.drop_constraint(None, 'users_roles', type_='foreignkey')
    op.create_foreign_key(op.f('users_roles_created_by_fkey'), 'users_roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_roles_updated_by_fkey'), 'users_roles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('users_roles', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users_roles', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'users_groups', type_='foreignkey')
    op.drop_constraint(None, 'users_groups', type_='foreignkey')
    op.create_foreign_key(op.f('users_groups_updated_by_fkey'), 'users_groups', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_groups_created_by_fkey'), 'users_groups', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('users_groups', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users_groups', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_created_by_fkey'), 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_updated_by_fkey'), 'users', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('tags_updated_by_fkey'), 'tags', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tags_created_by_fkey'), 'tags', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('tags', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tags', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'shared_nodes', type_='foreignkey')
    op.drop_constraint(None, 'shared_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('shared_nodes_created_by_fkey'), 'shared_nodes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('shared_nodes_updated_by_fkey'), 'shared_nodes', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('shared_nodes', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('shared_nodes', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_created_by_fkey'), 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('roles_updated_by_fkey'), 'roles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('roles', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('roles', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.create_foreign_key(op.f('nodes_created_by_fkey'), 'nodes', 'users', ['created_by'], ['id'], ondelete='SET NULL', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(op.f('nodes_updated_by_fkey'), 'nodes', 'users', ['updated_by'], ['id'], ondelete='SET NULL', initially='DEFERRED', deferrable=True)
    op.alter_column('nodes', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('nodes', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_created_by_fkey'), 'groups', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('groups_updated_by_fkey'), 'groups', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('groups', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('groups', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.create_foreign_key(op.f('document_versions_created_by_fkey'), 'document_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('document_versions_updated_by_fkey'), 'document_versions', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('document_versions', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('document_versions', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'document_types', type_='foreignkey')
    op.drop_constraint(None, 'document_types', type_='foreignkey')
    op.create_foreign_key(op.f('document_types_updated_by_fkey'), 'document_types', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('document_types_created_by_fkey'), 'document_types', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('document_types', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('document_types', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'custom_fields', type_='foreignkey')
    op.drop_constraint(None, 'custom_fields', type_='foreignkey')
    op.create_foreign_key(op.f('custom_fields_created_by_fkey'), 'custom_fields', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('custom_fields_updated_by_fkey'), 'custom_fields', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('custom_fields', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('custom_fields', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
