"""add group flags: delete_me and delete_special_folders

Revision ID: 973801cf0c71
Revises: 2518bf648ffd
Create Date: 2025-03-17 08:38:41.676748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973801cf0c71'
down_revision: Union[str, None] = '2518bf648ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('delete_me', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('delete_special_folders', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'delete_special_folders')
    op.drop_column('groups', 'delete_me')
    # ### end Alembic commands ###
