"""remove page status related fields

Revision ID: b2350127890a
Revises: 1240862ec13d
Create Date: 2025-06-29 12:58:54.277045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2350127890a'
down_revision: Union[str, None] = '1240862ec13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'preview_error_md')
    op.drop_column('pages', 'preview_error_xl')
    op.drop_column('pages', 'preview_status_lg')
    op.drop_column('pages', 'preview_status_md')
    op.drop_column('pages', 'preview_status_sm')
    op.drop_column('pages', 'preview_error_sm')
    op.drop_column('pages', 'preview_error_lg')
    op.drop_column('pages', 'preview_status_xl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('preview_status_xl', postgresql.ENUM('ready', 'pending', 'failed', name='preview_status'), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('preview_error_lg', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('preview_error_sm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('preview_status_sm', postgresql.ENUM('ready', 'pending', 'failed', name='preview_status'), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('preview_status_md', postgresql.ENUM('ready', 'pending', 'failed', name='preview_status'), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('preview_status_lg', postgresql.ENUM('ready', 'pending', 'failed', name='preview_status'), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('preview_error_xl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('preview_error_md', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
