"""add on casecase=delete for tags association table

Revision ID: bafd773c8533
Revises: 88b6b2d497ea
Create Date: 2025-02-01 08:59:18.660765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafd773c8533'
down_revision: Union[str, None] = '88b6b2d497ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nodes_tags_tag_id_fkey', 'nodes_tags', type_='foreignkey')
    op.create_foreign_key(None, 'nodes_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes_tags', type_='foreignkey')
    op.create_foreign_key('nodes_tags_tag_id_fkey', 'nodes_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
