version: 1
disable_existing_loggers: false

formatters:
  verbose:
    format: '%(levelname)s:%(pathname)s:%(lineno)d:%(funcName)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose

loggers:
  oidc_app:
    level: INFO
    handlers: [console]
  s3worker:
    level: DEBUG
    handlers: [console]
  papermerge.search.tasks:
    level: INFO
    handlers: [console]
    propagate: no
