export type PanelComponent =
  | "commander"
  | "viewer"
  | "searchResults"
  | "sharedCommander"
  | "sharedViewer"
  | "auditLogList"
  | "auditLogDetails"
  | "rolesList"
  | "roleDetails"
  | "groupsList"
  | "groupDetails"
  | "documentTypesList"
  | "documentTypeDetails"
  | "customFieldsList"
  | "customFieldDetails"
  | "usersList"
  | "userDetails"
