name: Build docker image for arm64

on:
  workflow_dispatch:
    inputs:
      VERSION:
        type: string
        required: true
      FRONTEND_TAG:
        type: string
        required: true
        default: latest

jobs:
  build-headless:
    name: arm64 headless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: papermerge/papermerge:${{ inputs.VERSION }}-headless
          file: docker/prod/Dockerfile
          platforms: linux/arm64

  dispatch-event-build-docker-image:
    name: Trigger build arm64 docker image with UI
    needs: [ build-headless ]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dispatch event
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT_TRIGGER_BUILD_DOCKER_IMAGE_WITH_UI }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'papermerge',
              repo: 'docker',
              workflow_id: 'build-arm64.yml',
              ref: 'master',
              inputs: {
                 INPUT_BACKEND_TAG: '${{ inputs.VERSION }}-headless',
                 INPUT_FRONTEND_TAG: '${{ inputs.FRONTEND_TAG }}'
              }
            })
