name: Build and Publish Docker Image

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true

jobs:
  build-and-push-image-to-docker-hub:
    name: Build and Push Image to DockerHub
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: papermerge/papermerge

      - name: Build and push with MANUAL tag
        uses: docker/build-push-action@v2
        if: ${{ github.event.inputs.tag != '' }}
        with:
          push: true
          tags: papermerge/papermerge:${{ github.event.inputs.tag }}
          file: docker/prod/Dockerfile

      - name: Build and push with RELEASE version as tag
        uses: docker/build-push-action@v2
        if: ${{ github.event.inputs.tag == '' }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: docker/prod/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
  build-and-push-image-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/papermerge/papermerge

      - name: Build and push with MANUAL tag
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        if: ${{ github.event.inputs.tag != '' }}
        with:
          push: true
          tags: papermerge/papermerge:${{ github.event.inputs.tag }}
          file: docker/prod/Dockerfile

      - name: Build and push with RELEASE version
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        if: ${{ github.event.inputs.tag == '' }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: docker/prod/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
