name: Publish to Dockerhub

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  publish-to-dockerhub:
    name: Publish to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: papermerge/papermerge:${{ inputs.VERSION }}
          file: docker/prod/Dockerfile
          platforms: linux/amd64,linux/arm64
